language: java
jdk:
- oraclejdk8
script:
- mvn clean install sonar:sonar
after_success:
- bash <(curl -s https://codecov.io/bash)
before_deploy:
- openssl aes-256-cbc -K $encrypted_e24db14852c4_key -iv $encrypted_e24db14852c4_iv -in deploy_rsa.enc -out /tmp/deploy_rsa -d
- eval "$(ssh-agent -s)"
- chmod 600 /tmp/deploy_rsa
- ssh-add /tmp/deploy_rsa
deploy:
  provider: script
  skip_cleanup: true
  script: rsync -r --delete-after --quiet $TRAVIS_BUILD_DIR/target/*.jar build@tlsfree.org:/home/build/theskeleton-$TRAVIS_BUILD_ID.jar && ssh -t build@tlsfree.org 'if pgrep -f theskeleton &> /dev/null ; then kill `pgrep -f theskeleton` ; fi' && ssh -t build@tlsfree.org 'nohup /home/build/theskeleton-$TRAVIS_BUILD_ID.jar --logging.file=/home/build/theskeleton-$TRAVIS_BUILD_ID.log &'
addons:
  sonarqube:
    organization: codenergic
    token:
      secure: C/bwhQsjwpKg7qaw5ZPvrlsNZ1YCS4HJxvH/VmQmtyskm333Dc6md4ZttcGc68Uepvh6SSBmOp9oGy2Z2tOQzgiyLBgRiC1BJb8KHAHReNiAgCbwldL4tstPZqGUa6bpcap5b5xLEyMN5O2V3D+uuXBGd/QMsC88a5ECeXqh2mz9lWLcACeOPSleT5Hk/SKB51j6Ri4gCIeRhKIlYgTbE54wYyKV/l1dZ+7dcsohfZmTgCSxXnzuNg9LlHFO1/zOUztNtW17P4yH8WwZDVoQfGvOFgxRwRYF90dFdw9a7nVHVseXMZUz/0olu60isbI/HCAarRFzpDORKsMYJpXfGlQQFtJSLzK64STEKGroryLf4JYwwrkL7SUxw434UH7h6JTDhatB0g4v0jhql07316o8HrqcMh614oyXW+ww3IPyyZ3ILNCezb+qJSWeM1w3ettabX4KvbUzdFVQivn2WKuVPpO6oCo2GmRwlcp2RnDv9fnY+rTWN8ukQ2tvhD9rXmGTJ7PydzKEW9Ju56XetcPUJdzLGFrsSG5/TccEtVaqBFKk3i9h5DIXtqRkw6/Ja0I2X8nKgnBWtqW/xOSpmuLcqH2ktfkDGD2oQCPUdwn3Mb2zfmhQOlUrAhegibZNu99lWLW2hEvhoOFJKKjn5dHQtcbElzXTRQ7zCb/kQk0=
  ssh_known_hosts:
  - tlsfree.org
