info:
  app:
    encoding: "@project.build.sourceEncoding@"
    artifact:
      artifactId: "@project.artifactId@"
      groupId: "@project.groupId@"
      version: "@project.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
logging:
  level:
    org.codenergic.theskeleton: DEBUG
management:
  context-path: /manage
  info:
    git:
      mode: full
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: DISABLE_SELECTIVE
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/generated-sources/database-schema.sql
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
  datasource:
    url: jdbc:h2:~/.theskeleton
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /manage/database
---
spring:
  profiles: mariadb
  datasource:
    url: jdbc:mariadb://localhost/theskeleton
    username: root
    password: root