info:
  app:
    encoding: "@project.build.sourceEncoding@"
    artifact:
      artifactId: "@project.artifactId@"
      groupId: "@project.groupId@"
      version: "@project.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
logging:
  level:
    org.codenergic.theskeleton: DEBUG
management:
  context-path: /manage
  info:
    git:
      mode: full
s3:
  client:
    endpoint: http://localhost:8082
    access-key: supersecret
    secret-key: supersecret123
security:
  oauth2:
    resource:
      filter-order: 3
spring:
  datasource:
    url: jdbc:h2:~/.theskeleton
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /manage/database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: DISABLE_SELECTIVE
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
  mail:
    host: localhost
    port: 1025
    username:
    password:
    properties:
      sender: theskeleton@codenergic.org
      senderAlias: TheSkeleton
      mail:
        smtp:
          auth: true
          starttls:
            enable: false
            required: false
