info:
  app:
    encoding: "@project.build.sourceEncoding@"
    artifact:
      artifactId: "@project.artifactId@"
      groupId: "@project.groupId@"
      version: "@project.version@"
    java:
      source: "@java.version@"
      target: "@java.version@"
logging:
  level:
    org.codenergic.theskeleton: DEBUG
management:
  context-path: /manage
  info:
    git:
      mode: full
security:
  oauth2:
    resource:
      filter-order: 3
spring:
  datasource:
    url: jdbc:h2:~/.theskeleton
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /manage/database
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          sharedCache:
            mode: DISABLE_SELECTIVE
      hibernate:
        cache:
          region:
            factory_class: org.hibernate.cache.ehcache.EhCacheRegionFactory
          use_second_level_cache: true
  mail:
    host: localhost
    port: 25
    username:
    password:
    mail:
      transport:
        protocol: smtp
      smtp:
        auth: false
        starttls:
          enable: false