logging:
  level:
    org.codenergic.theskeleton: DEBUG
spring:
  jpa:
    hibernate:
      ddl-auto: validate
    properties:
      javax:
        persistence:
          schema-generation:
            create-source: metadata
            scripts:
              action: create
              create-target: target/generated-sources/database-schema.sql
  datasource:
    url: jdbc:mariadb://localhost/theskeleton
    username: root
    password: root